### ISSUE TITLE
osTicket failed during Installation

### ISSUE THREAD

**Issue by dbflexi** [YunoHost-Apps/osticket_ynh#26]
*osTicket Installation bug*
I tried to install osTicket on a actual YNH different times and reveice errors. The log can be found here:
https://paste.yunohost.org/raw/ejabojagak

Maybe somebody have an idea how to solve this?

I tried installation:
- on different domains
- with/ without subfolder
- different laguages
- after restart and check for updates

I use YNH (version 4.2.8.3) on a provider-based VPS.

2021-09-21 14:05:51,023: ERROR - Installation von osticket fehlgeschlagen: Im Installationsscript ist ein Fehler aufgetreten

**Comment by yalh76** [comment]
Can you try to install the last version 1.16~ynh1 ?
