### ISSUE TITLE
Upgrade to 1.16 fails due to wrong php-version

### ISSUE THREAD

**Issue by YuleZ** [YunoHost-Apps/osticket_ynh#39]
### Describe the bug

After upgrading to 1.16 via YunoHost-WebApp, osTicket asks me to upgrade in the app itself.
I cannot upgrade there because osTicket want's to have php8 installed but only finds 7.33.

Is osTicket maybe not using a wrapper around php?

### Context

- Hardware: root-server
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH & through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: nothing special - master I guess
- If upgrading, current package version: now it's 1.16 - it was 1.15.x 

### Steps to reproduce

- upgrade osTicket from 1.15.x to 1.16 in yunohost-WebApp
- surf the osTicket-Application

### Expected behavior
I want to upgrade to 1.16 completely

### Logs
[Can be found here](https://paste.yunohost.org/raw/ohijudufen)

**Comment by yalh76** [comment]
If I understand, you tried to upgrade the app not using yunohost but directly inside Osticket ?

**Comment by YuleZ** [comment]
No, via yunohost. But in the Webapp, not via CLI

**Comment by yalh76** [comment]
and inside OsTicket, it proposed to upgrade to which version ?

**Comment by yalh76** [comment]
Ok then, i've installed and upgrade osticket. so now  I see it. inside osticket, it the admin part, it ask to upgrade ..
![image](https://user-images.githubusercontent.com/30271971/154584568-869e3203-ef57-4a1b-8d9a-d3037b85b834.png)

**Comment by yalh76** [comment]
ok, found it ..
Quick and dirty :
you can edit /var/www/osticket/include/class.setup.php
and replace :
`'php' => '8.0',` 
by
`'php' => '7.2',`

you then will be able to upgrade

**Comment by YuleZ** [comment]
sounds really dirty.
Will osTicket not use any php8 features which wouldn't be available if I bypass this validation?

**Comment by yalh76** [comment]
I don't know, it was just a quick and dirty solution to let you use osticket

but there is an ongoing PR to 1.16.1 with PHP8
