### ISSUE TITLE
osticket fails to install x64 dedicated server 

### ISSUE THREAD

**Issue by bh-cod4r** [YunoHost-Apps/osticket_ynh#62]
Dedicated Server (Intel i3 with 8GB Ram)

[YunoHost](https://yunohost.org/) 11.1.17 (stable)

The app fails to install - this is a new ynh install no other apps have been installed

tried installing the app from the ynh web page , i have ssh access to the server if needed.

here are the logs: if the logs are not visible using the url, please let me know - thank you

Application: osticket
https://paste.yunohost.org/raw/nizenajuse

**Comment by yalh76** [comment]
The error is : `2023-04-13 20:06:20,192: WARNING - mkdir: cannot create directory ‘/var/www’: Permission denied`

You didn't execute the install as root or using sudo
